name: Compile and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/curvineio/curvine-compile:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust toolchain
        run: |
          export PATH="/root/.cargo/bin:$PATH"
          unset RUSTUP_UPDATE_ROOT
          unset RUSTUP_DIST_SERVER
          rustup default 1.86.0
          rustc --version
          cargo --version
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "curvine-build"
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run fmt
        run: cargo fmt --check
        
      - name: Run clippy
        env:
          CLIPPY_LEVEL: deny 
        run: cargo clippy --release --all-targets -- --${CLIPPY_LEVEL}=warnings